name: DummyCheck

on:
  pull_request:
    branches: [ main ]

env:
  # renovate: datasource=github-tags depName=golang/go
  # extractVersion=^go(?<version>.*)$
  GOLANG_VERSION: "1.19.10"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3
