name: DummyCheck

on:
  pull_request:
    branches: [ main ]

env:
  GOLANG_VERSION: "1.19.5"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3
